[project]
name = "rowblaze"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "networkx>=3.5",
    "openpyxl>=3.1.5",
    "streamlit>=1.48.0",
    "watchdog>=6.0.0",
]
